### ISSUE TITLE
Error-Feature request

### ISSUE THREAD

**Issue by Bergerie** [bertmelis/SDS011#1]
I'm trying to use yr example but unfortunatley it keeps coming up with the following error at 👍 
  sds011.onResponse([](){
    // command has been executed
  });
 error: no matching function for call to 'SDS011::onResponse(setup()::__lambda5)'

Moreover, my MQTT broker uses an mqttusername and mqttpassword, could that be implemented.
Thnks in advance.

**Comment by bertmelis** [comment]
I've updated the example: https://github.com/bertmelis/SDS011/pull/3

For mqtt try this:

```cpp
mqttClient.setCredentials("username", "password");
```
